// Generated by CoffeeScript 1.6.3
var activity, manager, managers, site;

if (!tired) {
  keepRunning();
}

if (focus !== extremelyLow) {
  keepWorking;
}

if (pant(onFire)) {
  look(forWater());
}

if (game !== good) {
  badMouth();
}

if (tired && bored) {
  sleep();
} else {
  jog();
}

while (work > time) {
  freakOut();
}

while (!(exhaustion > energy)) {
  workOut;
}

activity = sunday ? isChilling : isWorking;

while (!(energy < exhaustion)) {
  workOut();
}

managers = {
  'CodeCanyon': 'Jeffrey Way',
  'Theme Forest': 'Mark Brodhuber',
  'ActiveDen': 'Lance Snider'
};

for (site in managers) {
  manager = managers[site];
  alert(manager + "manages" + site);
}
