// Generated by CoffeeScript 1.6.3
var hideMenu, oldMenu, toggleMenu;

hideMenu = function(elementname, classname) {
  var allElements, currentElement, _i, _len, _results;
  allElements = document.getElementsByTagName(elementname);
  _results = [];
  for (_i = 0, _len = allElements.length; _i < _len; _i++) {
    currentElement = allElements[_i];
    if (currentElement.className === classname) {
      _results.push(currentElement.style.display = 'none');
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

oldMenu = null;

toggleMenu = function(currId) {
  var currMenu;
  currMenu = document.getElementById(currId);
  if (oldMenu) {
    oldMenu.style.display = 'none';
  }
  currMenu.style.display = 'block';
  oldMenu = currMenu;
};
